In [69]:
import numpy as np

In [219]:
f = lambda t,y : y-t**2+1  #dydt=f(t,y)

In [220]:
def Euler(f,a,b,C_inicial,N): # a= tiempo inicial b= tiempo final 
    h=(b-a)/N
    t=a    
    w=C_inicial

    lista = np.zeros((N+1,2))
    
    for i in range(N+1):
        t=a+i*h
        lista[i][0]=t 
        lista[i][1]=w
        w+=h*f(t,w)

    return lista # (t,w)
        

In [269]:
def RK_O4(f,a,b,C_inicial,N): #Runge-Kutta de orden 4
    h=(b-a)/N
    t=a
    w=C_inicial
    
    lista=np.zeros((N+1,2))
    
    for i in range(N+1):
        K1=h*f(t,w)
        K2=h*f(t+h*.5,w+K1*.5)
        K3=h*f(t+h*.5,w+K2*.5)
        K4=h*f(t+h,w+K3)
        
        lista[i][0], lista[i][1]= t, w
        
        w+=(K1+2*K2+2*K3+K4)/6
        t=a+i*h
           
    return lista

In [271]:
f1 = lambda t,I1,I2: -4*I1+3*I2+6
f2 = lambda t,I1,I2: -2.4*I1+1.6*I2+3.6

Initial_Condition_list=[0,0]
f_list=[f1,f2]

def RK_04System(f,a,b,IC_list,N): #u′j = fj(t, u1, u2, . . . , um) , [a,b] equally spaced interval
    h=(b-a)/N
    t=a
    m=len(IC_list)
    k_list=np.zeros((4,m))
    w=np.zeros(m)
    t_w_list=np.zeros((N+1,m+1))
    t_list=[]
    
    for j in range(m):
        w[j]=IC_list[j]
        
    for i in range(N+1):
        for j in range(m):
            k_list[0][j]=h*f[j](t,w[0],w[1])
            k_list[1][j]=h*f[j](t+h*.5,w[0]+.5*k_list[0][0],w[1]+.5*k_list[0][1])
            k_list[2][j]=h*f[j](t+.5*h,w[0]+.5*k_list[1][0],w[1]+.5*k_list[1][1])
            k_list[3][j]=h*f[j](t+h,w[0]+k_list[2][0],w[1]+k_list[2][1])
   
            t_w_list[i][j+1]=w[j]
            t_w_list[i][0]=t

            w[j]+=(k_list[0][j]+2*k_list[1][j]+2*k_list[2][j]+k_list[3][j])/6
            t=a+i*h
            print(k_list)
   # return t_w_list

In [272]:
RK_04System(f_list,0,.5,Initial_Condition_list,5)

[[0.6    0.    ]
 [0.48   0.    ]
 [0.504  0.    ]
 [0.3984 0.    ]]
[[0.6        0.241344  ]
 [0.48       0.18865152]
 [0.504      0.19883612]
 [0.3984     0.15219778]]
[[0.46066585 0.241344  ]
 [0.40473428 0.18865152]
 [0.40801672 0.19883612]
 [0.35711    0.15219778]]
[[0.46066585 0.17477334]
 [0.40473428 0.13347531]
 [0.40801672 0.13688325]
 [0.35711    0.09875065]]
[[0.33849272 0.17477334]
 [0.29701017 0.13347531]
 [0.29911198 0.13688325]
 [0.2599129  0.09875065]]
[[0.33849272 0.12486044]
 [0.29701017 0.09423015]
 [0.29911198 0.09675763]
 [0.2599129  0.06855479]]
[[0.24788559 0.12486044]
 [0.21703754 0.09423015]
 [0.21861261 0.09675763]
 [0.18946784 0.06855479]]
[[0.24788559 0.08785804]
 [0.21703754 0.06514042]
 [0.21861261 0.06702477]
 [0.18946784 0.04611498]]
[[0.18055718 0.08785804]
 [0.15762445 0.06514042]
 [0.15880335 0.06702477]
 [0.13714327 0.04611498]]
[[0.18055718 0.06045723]
 [0.15762445 0.04362694]
 [0.15880335 0.04503245]
 [0.13714327 0.02954961]]
[[0.13055306 0.0604572